name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Lint, format & typecheck
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup pnpm
        uses: pnpm/action-setup@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: install dependencies
        run: pnpm i --frozen-lockfile

      - name: lint (oxlint)
        run: pnpm lint

      - name: format (oxfmt)
        run: pnpm format:check

      - name: typecheck (tsc)
        run: pnpm typecheck
